export const projects = [
  {
    title: 'Budget',
    subtitle:"Cotizacion estimada",
    description: "El servicio de BUDGET (propuesta) es uno de los servicios mas rapidos el cual ofrece una lista de materiales de controles estimado",
     subdescriptions: [ 'test', 'test2' ], 
    image: '/images/budget1.jpg',
      tags: ['BOM', 'Documentos Trabajados'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'BOM',
    subtitle:"Lista de Materiales",
    description:"El servicio de BOM (Lista de Materiales) ofrece una lista de materiales precisa a los planos eléctricos, especificaciones y secuencia de operación del proyecto",
    subdescriptions: [ 'test', 'test2'  ],
    image: '/images/BOM1.jpg',
    tags: ['BOM', 'Documentos Trabajados'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Layout',
    subtitle:"Diseño de controles",
    description: "El servicio de Layout este servicio incluye la lista de materiales, los planos con todos los detalles sobre el producto, notas e instrucciones de instalación",
     subdescriptions: [ 'test', 'test2'  ], 
    image: '/images/Layout1.jpg',
      tags: ['BOM', 'Diseño de control (Planos)', 'Documentos Trabajados' ],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Submittal',
    subtitle:"Paquete de envío",
    description: "El servicio de Submittal Package este servicio es normalmente solicitado en las fases finales del proyecto donde se requiere incluir toda información sobre el proyecto",
    subdescriptions: [ 'secuencia de operacion', 'Diagramas de risers ', 'Fichas tecnicas'  ],
    image: '/images/submittal1.jpg',
    tags: ['BOM', 'Diseño de control (Planos)', 'Documentos Trabajados'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
    {
      title: 'Diagramas',
      subtitle:"Cableados e Instrucciones",
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    subdescriptions: [ 'test', 'test2'  ],
      image: '/images/diagrams1.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
      {
        title: 'QC',
        subtitle:"Control de Calidad",
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    subdescriptions: [ 'test', 'test2'  ],
        image: '/images/QC1.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: "Cliente", text: 'Started my journey', },
  { year: "Agencia", text: 'Worked as a freelance developer', },
  { year: "DAS", text: 'Founded JavaScript Mastery', },
  { year: "RFA", text: 'Shared my projects with the world', },
  { year: "QUOTE", text: 'Started my own platform', },
];